# Generated by Django 4.2.1 on 2024-05-11 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_0', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
